version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns: ["*"]
