[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/ljufa/rsplayer-cross-armv7:latest"

[target.arm-unknown-linux-gnueabihf]
image = "ljufa/rsplayer_cross_armhf:0.0.1"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/ljufa/rsplayer-cross-aarch64:latest"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/ljufa/rsplayer-cross-x86_64:latest"

[target.riscv64gc-unknown-linux-gnu]
image = "ghcr.io/ljufa/rsplayer-cross-riscv64:latest"
