FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:0.2.2
RUN dpkg --add-architecture armhf
RUN apt update
RUN apt-get install -y libasound-dev:armhf
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
ENV PKG_CONFIG_ALLOW_CROSS=1
