[env]
# RPI_HOST = "192.168.5.3"
# TARGET = "arm-unknown-linux-gnueabihf"

RPI_HOST = "192.168.5.4"
TARGET = "aarch64-unknown-linux-gnu"


RELEASE_VERSION = "1.2.1"
RELEASE_BRANCH = "main_public"

[config]
default_to_workspace = false


# ---- BUILD Backend----

[tasks.build_release]
command = "cross"
args = [
    "build",
    "--target",
    "${TARGET}",
    "--release",
    "--package",
    "rsplayer",
    "--bin",
    "rsplayer",
]
[tasks.build_debug]
command = "cross"
args = [
    "build",
    "--target",
    "${TARGET}",
    "--package",
    "rsplayer",
    "--bin",
    "rsplayer",
]
[tasks.build_ui_release]
cwd = "rsplayer_web_ui"
command = "cargo"
args = ["make", "build_release"]

[tasks.package_deb_release]
command = "cargo"
args = [
    "deb",
    "--no-build",
    "-p",
    "rsplayer",
    "--target=${TARGET}",
    "--deb-version",
    "${RELEASE_VERSION}",
]

# ---- LINT ----
[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = [
    "clippy",
    "--fix",
    "--allow-dirty",
    "--allow-staged",
    "--all-features",
    "--",
    "--deny",
    "warnings",
    "--deny",
    "clippy::pedantic",
    "--deny",
    "clippy::nursery",
    "--allow",
    "clippy::use_self",
    "--allow",
    "clippy::module_name_repetitions",
    "--allow",
    "clippy::must_use_candidate",
    "--allow",
    "let_underscore_drop",
    "--allow",
    "clippy::missing_panics_doc",
    "--allow",
    "clippy::missing_errors_doc",
    "--allow",
    "clippy::use_self",
    "--allow",
    "clippy::significant-drop-tightening",
    "--allow",
    "clippy::similar_names",
]

[tasks.clippy_in_cross]
description = "Lint with clippy in the pipeline"
command = "cross"
args = [
    "clippy",
    "--target",
    "${TARGET}",
    "--",
    "--deny",
    "warnings",
    "--deny",
    "clippy::pedantic",
    "--deny",
    "clippy::nursery",
    "--allow",
    "clippy::use_self",
    "--allow",
    "clippy::module_name_repetitions",
    "--allow",
    "clippy::must_use_candidate",
    "--allow",
    "let_underscore_drop",
    "--allow",
    "clippy::missing_panics_doc",
    "--allow",
    "clippy::missing_errors_doc",
    "--allow",
    "clippy::use_self",
    "--allow",
    "clippy::significant-drop-tightening",
    "--allow",
    "clippy::similar_names",
]

[tasks.test_in_cross]
command = "cross"
args = ["test", "--target", "${TARGET}"]

[tasks.format]
description = "Format with rustfmt"
command = "cargo"
args = ["fmt"]

# ---- Local DEV ----
[tasks.kill_local]
script = "sudo pkill -9 rsplayer || true"

[tasks.run_local]
dependencies = ["kill_local"]
env = { "RUST_LOG" = "rsplayer=info,rsplayer_playback=debug,warp=info", "RUST_BACKTRACE" = "full", "PORT" = "8000", "TLS_PORT" = "8443", "TLS_CERT_PATH" = "self.crt", "TLS_CERT_KEY_PATH" = "self.key" }
cwd = ".run"
command = "cargo"
args = ["run"]

[tasks.copy_remote]
dependencies = ["build_release"]
script = [
    "rsync -avvP --rsync-path=\"sudo rsync\" target/${TARGET}/release/rsplayer pi@${RPI_HOST}:/usr/bin",
    "ssh -x pi@${RPI_HOST} \"sudo systemctl restart rsplayer\""
]
[tasks.copy_remote_debug]
dependencies = ["build_debug"]
script = [
    "rsync -avvP --rsync-path=\"sudo rsync\" target/${TARGET}/debug/rsplayer pi@${RPI_HOST}:/usr/bin",
]

[tasks.package_deb_local]
dependencies = ["build_ui_release", "build_release", "package_deb_release"]
script = "rsync -avvP target/${TARGET}/debian/*.deb pi@${RPI_HOST}:~"

[tasks.tag]
script = [
    "git tag ${RELEASE_VERSION} ${RELEASE_BRANCH}",
    "git push originpublic ${RELEASE_VERSION}",
]
