#!/usr/bin/env bash
if [ "$1" = "configure" ]; then
    if [ -z $2 ]
    # this is clean install
    then 
        echo "No previous version found this is clean install"
        adduser --system --no-create-home --disabled-login rsplayer
        usermod -a -G audio rsplayer
        # optional for hardware access
        usermod -a -G i2c,gpio,spi,input rsplayer || true
        mkdir -p /opt/rsplayer
        chown -R rsplayer /opt/rsplayer
    #this is upgrade
    else
        echo "Previous version found: $2"
        VERSION_TO_COMPARE="0.9.1"
        if [ "$(printf '%s\n' "$VERSION_TO_COMPARE" "$2" | sort -V | head -n1)" = "$VERSION_TO_COMPARE" ]; then
            echo "$2 is greater than $VERSION_TO_COMPARE"
        else
            echo "$2 is not greater than $VERSION_TO_COMPARE"
            adduser --system --no-create-home --disabled-login rsplayer
            usermod -a -G audio rsplayer
            # optional for hardware access
            usermod -a -G i2c,gpio,spi,audio,input rsplayer || true
            chown -R rsplayer /opt/rsplayer
        fi
    fi
    systemctl daemon-reload
    systemctl enable rsplayer
    systemctl start rsplayer
fi
