#!/usr/bin/env bash
if [ "$1" = "configure" ]; then
    if [ -z $2 ]
    then 
        # this is clean install
        previous_version="0.0.0"
    else
        # this is upgrade
        previous_version=$2
    fi
    if dpkg --compare-versions "$previous_version" lt "0.9.1"; then
        echo "Upgrading from version $previous_version to 0.9.1"
        adduser --system --no-create-home --disabled-login rsplayer
        usermod -a -G audio rsplayer
        # optional for hardware access
        usermod -a -G i2c,gpio,spi,audio,input rsplayer || true
        chown -R rsplayer /opt/rsplayer
    fi
    if dpkg --compare-versions "$previous_version" lt "0.9.7"; then
        echo "Upgrading from version $previous_version to 0.9.7"
        chown rsplayer /opt/rsplayer/env
        chown rsplayer /opt/rsplayer/self.*
    fi
    systemctl daemon-reload
    systemctl enable rsplayer
    systemctl start rsplayer
fi
