FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.5

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libssl-dev \
        libasound-dev \
        libasound2-dev && \
    rm -rf /var/lib/apt/lists/*
