FROM ghcr.io/cross-rs/riscv64gc-unknown-linux-gnu:0.2.5

RUN dpkg --add-architecture riscv64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libasound-dev:riscv64 && \
    rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_PATH=/usr/lib/riscv64-linux-gnu/pkgconfig
ENV PKG_CONFIG_ALLOW_CROSS=1
