FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libssl-dev:arm64 \
        libasound-dev:arm64 \
        libasound2-dev:arm64 && \
    rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
ENV PKG_CONFIG_ALLOW_CROSS=1
