== Raspbery PI 4 with Ubuntu Server arm64 installation

=== Setup os (optional)
* update and change user pass
[source, bash]
sudo apt update
sudo apt upgrade
passwd
sudo reboot

* install micro
[source]
curl https://getmic.ro | bash
sudo mv micro /usr/bin

* install zsh  https://github.com/ohmyzsh/ohmyzsh
[source]
sudo apt install -y zsh git fzf
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions


=== Mount network share
[source]
sudo apt install -y cifs-utils
sudo cp fstab /etc/fstab
sudo mkdir /media/samsung
sudo mount /media/samsung
sudo mkdir /home/music
sudo ln -s /media/samsung/MUSIC /home/music


=== Build librespot
[source, bash]
cd github
git clone git@github.com:librespot-org/librespot.git && cd librespot
cp ../dplauer/Cross.toml .
cross build --target aarch64-unknown-linux-gnu --release --no-default-features --features alsa-backend

OR
[source, bash]
make build_librespot

=== Create dplay as service
[source]
sudo cp dplay.service /etc/systemd/system/
sudo systemctl enable dplay.service
sudo systemctl start dplay.service

=== Install mpd
[source]
sudo apt install -y mpd
# then remove service files to avoid automatic mpd start
sudo rm /etc/systemd/user/sockets.target.wants/mpd.socket
sudo rm /etc/systemd/system/sockets.target.wants/mpd.socket
sudo systemctl daemon-reload

# old way, disable mpd 
// sudo systemctl disable mpd.service
// sudo systemctl disable mpd.socket
// sudo rm /usr/lib/systemd/system/mpd.service
// sudo rm /usr/lib/systemd/system/mpd.socket


=== WIFI setup
[source]
sudo cp wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf

=== LIRC setup
put 
```
dtoverlay=gpio-ir,gpio_pin=27
gpio=18,15,17=pu
gpio=22,23,9=op,dh
``` 
into `/boot/config.txt`

[source]
sudo apt-get install -y lirc
sudo cp lirc_options.conf /etc/lirc/lirc_options.conf

==== setup new remote
[source]
irdb-get download apple/A1156.lircd.conf
sudo cp A1156.lircd.conf /etc/lirc/lircd.conf.d
irrecord -d /dev/lirc0 dplayd.lircd.conf
sudo cp dplayd.lircd.conf /etc/lirc/lircd.conf.d


=== Install LMS
[source, bash]
wget http://downloads.slimdevices.com/nightly/8.2/lms/6e12028145512cef7d240c5d24c3b17e89ed8a6d/logitechmediaserver_8.2.0\~1609139175_arm.deb
sudo dpkg -i logitechmediaserver_8.2.0\~1609139175_arm.deb
sudo apt --fix-broken install
wget wget https://sourceforge.net/projects/lmsclients/files/squeezelite/linux/squeezelite-1.9.9.1372-aarch64.tar.gz/download
tar zxvf download
sudo cp squeezelite /home/ubuntu
squeezelite -V "Luckit Audio 2.0 Output" -o hw:CARD=L20,DEV=0 -C 1 -v -z

