name: Build and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**.rs'
      - '**.toml'
      - '**/ci.yml'

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_backend:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/rsplayer-backend-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo make test
