name: Build and test
on:
  push:
    branches:
      - "main"
    paths:
      - '**.rs'
      - '**.toml'
      - '**/ci.yml'
env:
  CARGO_TERM_COLOR: always

jobs:
    
  build_backend:
    name: Build and test
    runs-on: rsplayer-self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: davidB/rust-cargo-make@v1
    - name: Clippy lint
      run: cargo make clippy
    - name: Run tests
      run: cargo make test
